OpenVPN
Otus-DevOps-2021-08/Ascalonking_infra pull request #13
Opened 2021-09-28 12:25 UTC by Ascalonking

Настройка VPN на YandexCloud

2021-09-29 19:01 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно помержить все изменения в мастер, и так же проверить что тесты работают. Сейчас у вас тесты не доступны потому что не было мержа =)

2021-09-29 19:06 UTC, Ascalonking commented
> Здравствуйте!) Вам нужно помержить все изменения в мастер, и так же проверить что тесты работают. Сейчас у вас тесты не доступны потому что не было мержа =)

как я понял в данном ДЗ надо было домашку делать на виртуалке в YC. Мой аккаунт в YC забанен.

2021-09-29 19:25 UTC, Ascalonking commented
> Здравствуйте!) Вам нужно помержить все изменения в мастер, и так же проверить что тесты работают. Сейчас у вас тесты не доступны потому что не было мержа =)

Под словом мастер вы имеете ввиду что надо закинуть в main?

2021-09-29 19:42 UTC, mrgreyves commented
Все верно, флешбеки. Раньше дефолтная ветка в новых репозиториях называлась master, не так что бы очень давно ее переименовали в main

2021-09-30 16:11 UTC, Ascalonking commented
Чтобы смержить в меин нужно выполнить следующую команду? `git merge cloud-bastion`

2021-10-02 10:34 UTC, mrgreyves commented
Да, но при этом вы можете смержить после апрува и через веб интерфейс. Так же у вас к этому дз снова нет тестов. Нужно поправить =)

2021-10-02 10:34 UTC, closed without merging