YC ver2
Otus-DevOps-2021-08/Ascalonking_infra pull request #16
Opened 2021-10-02 11:40 UTC by Ascalonking

Обналвенный branch

2021-10-03 20:47 UTC, mrgreyves requested changes
![image](https://user-images.githubusercontent.com/34331259/135771040-7dd8439c-0b30-4aee-966a-57291d576315.png)
Не вижу тестов

2021-10-04 00:04 UTC, Ascalonking commented
> ![image](https://user-images.githubusercontent.com/34331259/135771040-7dd8439c-0b30-4aee-966a-57291d576315.png) Не вижу тестов

Можно пожалуйста для мен (для жирафа) оставлять более развернутые ответы что конкретно требуется и что нужно сделать. Я уже совсем запутался что не то я делаю. Спасибо

2021-10-04 04:44 UTC, Ascalonking reviewed
просто коммит

2021-10-04 08:05 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-10-04 08:45 UTC, Ascalonking commented
Please merge

2021-10-04 09:08 UTC, merged