Cloud testapp
Otus-DevOps-2021-08/Ascalonking_infra pull request #17
Opened 2021-10-02 12:18 UTC by Ascalonking

2021-10-03 20:49 UTC, mrgreyves requested changes
Здравствуйте!
Проверил ваше дз.
Хорошо что есть тесты, плохо что они красные.
Обратите внимание на их результаты. В описании тестов достаточно подробно расписано где проблемы. ДЗ возвращаю на доработку

2021-10-04 05:33 UTC, Ascalonking commented
> Здравствуйте! Проверил ваше дз. Хорошо что есть тесты, плохо что они красные. Обратите внимание на их результаты. В описании тестов достаточно подробно расписано где проблемы. ДЗ возвращаю на доработку

Не могу понять проблемы. Тесты показывают что у меня не установлен ruby-full, ruby-bundler, mongodb-org
`yc-user@reddit-app:~$ sudo apt-get install ruby-full
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ruby-full is already the newest version (1:2.3.0+1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
yc-user@reddit-app:~$ sudo apt-get install ruby-bundler
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ruby-bundler is already the newest version (1.11.2-1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
yc-user@reddit-app:~$ sudo apt-get install mongodb-org
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mongodb-org is already the newest version (4.2.17).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.`

2021-10-04 06:59 UTC, Ascalonking commented
Всё, разобрался, моя невнимательность, не добавил к скриптам chmod +x

2021-10-04 08:04 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув =)

2021-10-04 08:06 UTC, merged